# tasks for Debian platform (Ubuntu)
---

- name: Install general build tools
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: [git, python-setuptools, python-dev, python-pip, python3-pip,
    build-essential, libreadline-dev, libffi-dev, libssl-dev, libyaml-dev,
    cmake, ninja-build, srecord]

- name: Install yotta
  pip:
    name: yotta

- name: Set git user email
  command: git config --global user.email \"{{ git_user_email }}\"

- name: Set git user name
  command: git config --global user.name \"{{ git_user_name }}\"

- name: Remove outdated ARM gcc and binutils
  sudo: yes
  apt:
    name: "{{ item }}"
    state: absent
  with_items: ["binutils-arm-none-eabi", "gcc-arm-none-eabi", "gcc-arm-embedded"]

- name: Add ppas
  sudo: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items: ["ppa:team-gcc-arm-embedded/ppa"]

# This installs newlib 2.2.0+git20150830.5a3d536-1
# We may need newlib 2.4.0-2
# TODO: Install newlib-2.4.0!
# <https://github.com/bbcmicrobit/micropython/issues/363#issuecomment-270890904>

- name: Install GCC ARM compiler and toolchain
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: ["gcc-arm-none-eabi=15:4.9.3+svn231177-1"]

# could also install cc-arm-embedded=6-2017q1-1* to get latest version from ppa
